version: "3.7"

services:
   web:
      build: ./django_project
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
         - ./django_project:/usr/src/app
      ports:
         - 8000:8000
      env_file:
         - ./.env.dev
      depends_on:
         db:
            condition: service_healthy

   db:
      image: postgres:15
      volumes:
         - postgres_data:/var/lib/postgresql/data/
      healthcheck:
         test: pg_isready -U "${SQL_USER:-user_name}" -d "${SQL_DATABASE:-db_name}" || exit 1
         interval: 10s
         timeout: 5s
         retries: 5
         start_period: 30s
      env_file:
         - ./.env.dev 

volumes:
   postgres_data: