# Generated by Django 5.0.2 on 2024-02-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nazoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riddlemodel',
            name='good',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='riddlemodel',
            name='read',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='riddlemodel',
            name='readtext',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
