# Generated by Django 4.2 on 2024-02-21 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nazoapp', '0002_alter_riddlemodel_good_alter_riddlemodel_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riddlemodel',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='既読ユーザー'),
        ),
    ]
