# Generated by Django 4.2 on 2024-02-21 10:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nazoapp', '0004_alter_riddlemodel_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riddlemodel',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='既読ユーザー'),
        ),
    ]
