# Generated by Django 5.0.2 on 2024-02-25 10:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nazoapp', '0002_alter_riddlemodel_good_alter_riddlemodel_read_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='riddlemodel',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='ブックマークユーザー'),
        ),
    ]
