# Generated by Django 5.0.2 on 2024-02-25 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nazoapp', '0003_riddlemodel_bookmarks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riddlemodel',
            name='good',
        ),
        migrations.RemoveField(
            model_name='riddlemodel',
            name='read',
        ),
        migrations.RemoveField(
            model_name='riddlemodel',
            name='readtext',
        ),
        migrations.AddField(
            model_name='riddlemodel',
            name='playings',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='riddlemodel',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='ブックマークユーザー'),
        ),
    ]
