# Generated by Django 5.0.2 on 2024-02-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nazoapp', '0004_remove_riddlemodel_good_remove_riddlemodel_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riddlemodel',
            name='time',
            field=models.CharField(choices=[('10', '〜15分'), ('30', '15分〜45分'), ('60', '45分〜90分'), ('120', '90分〜180分'), ('300', '180分〜')], max_length=10),
        ),
    ]
