# Generated by Django 5.0.2 on 2024-03-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nazoapp', '0007_rename_evaluationmodel_reviewmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riddlemodel',
            name='level',
            field=models.CharField(choices=[('1', '初級'), ('2', '中級'), ('3', '上級')], max_length=10),
        ),
    ]
