# Generated by Django 5.0.2 on 2024-03-12 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nazoapp', '0008_alter_riddlemodel_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riddlemodel',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
