# Generated by Django 5.0.2 on 2024-03-12 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nazoapp', '0009_alter_riddlemodel_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewmodel',
            old_name='level',
            new_name='rating_level',
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='rating_gimmick',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='rating_story',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='rating_sukkiri',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riddlemodel',
            name='rating_gimmick',
            field=models.FloatField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riddlemodel',
            name='rating_level',
            field=models.FloatField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riddlemodel',
            name='rating_story',
            field=models.FloatField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riddlemodel',
            name='rating_sukkiri',
            field=models.FloatField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
