# Generated by Django 5.0.2 on 2024-03-12 11:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nazoapp', '0010_rename_level_reviewmodel_rating_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riddlemodel',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
